exp_name: AE-shapenet_10000obj_under800_8channel_12en_768_18de_384_1e-4kl_1GCN_womask_ordered

# model related
dataset_name: shapenet
encoder_dim: 768
decoder_dim: 384
decoder_fine_dim: 256
graph_layers: 1
patch_size: 1
encoder_depth: 12
decoder_depth: 18
bin_smooth_blur_sigma: 0.4
quant_bit: 7
quant_face: False
num_discrete_coors: 128

# training realted
batch_size: 8
learning_rate: 1.0e-4
warmup_steps: 1000
weight_decay: 0.
max_grad_norm: 0.5
dropout: 0.
resume: null
grad_accum_every: 8
num_train_steps: 500000
val_every: 2000
checkpoint_every: 2000
latent_dim: 8

pos_embed: False

kl_regularization: True

augment_dict:
  scale_min: 0.95
  scale_max: 1.05
  rotation: 1
  jitter_strength: 0.01

# exp_name: AE-shapenet_14400*10_8channel_12en_768_18de_384_1e-4kl_1GCN_pos

# # model related
# dataset_name: shapenet
# encoder_dim: 512
# decoder_dim: 512
# decoder_fine_dim: 256
# graph_layers: 1
# patch_size: 1
# encoder_depth: 12
# decoder_depth: 12
# bin_smooth_blur_sigma: 0.4
# quant_bit: 7
# quant_face: False
# num_discrete_coors: 128

# # training realted
# batch_size: 4
# learning_rate: 1.0e-4
# warmup_steps: 1000
# weight_decay: 0.
# max_grad_norm: 0.5
# dropout: 0.
# resume: null
# grad_accum_every: 8
# num_train_steps: 500000
# val_every: 2000
# checkpoint_every: 2000
# latent_dim: 8

# pos_embed: True

# kl_regularization: False

# augment_dict:
#   scale_min: 0.95
#   scale_max: 1.05
#   rotation: 1
#   jitter_strength: 0.01